### ISSUE TITLE
Relation to dragos/dragos-vscode-scala

### ISSUE THREAD

**Issue by myknbani** [ensime/ensime-vscode#10]
It uses ensime as well, and even encourages donation to ensime 😁

**Comment by hedefalk** [comment]
Well, these are two different approaches. This one uses the same underlying node lib for communication with ensime server as ensime-atom, using the standard ensime protocol, while dragos' approach is embedding ensime-server using the vscode language protocol.

This one had been a bit dead I'm sorry to admit, as has ensime-atom for a while since I've been on parental "leave". I guess dragos' apprach has evolved more during the las few months.

 I will however start working again with Scala somewhere in the next few weeks. Dunno if I'm gonna stick with atom or go vscode yet. And if the later I'll look into dragos' version too and see which works best for me.

I haven't used this one much and I don't know if anyone is using it for "real work" yet but I think quite a few is using ensime-atom. And basically 90% could reusable between them. It's very little code to write the vscode ui stuff (when it works) since there really isn't any ui to write.

**Comment by myknbani** [comment]
Thanks for clarifying.  I'll just close this one. ^_^
